### PR TITLE
Fix issue when function arguments with mutiply class or struct keywords

### PR DESCRIPTION
**Pull request by yanj403**
Issue introduction:
CPPLint already have protection when function arguments with extra "class" or "struct" keywords, following scenario is fine:

          struct demo_struct {
              int field;
          };
          
          void demo_issue(int num,
              struct demo_struct const *new_struct1,
              )
          {
              return 0;
          }

But in case multiply "struct" function arguments existed in a function like below(add "new_struct2" parameter):

          struct demo_struct {
              int field;
          };
          
          void demo_issue(int num,
              struct demo_struct const *new_struct1,
              struct demo_struct const *new_struct2  
              )
          {
              return 0;
          }

 It will cause false positive reporting as below:
demo.cpp:11:  Closing brace should be aligned with beginning of struct demo_struct  [whitespace/indent] [3]

Issue analysis:
In case meet multiply struct parameters, will push "_ClassInfo" instances mutiply times into the "stack" array of NestingState class ,
when ";" or ")" token is encountered before OpenBrace is not seen, will pop ONLY one "_ClassInfo" instance from the stack.
that makes at least one "struct" parameters be regarded as a "_ClassInfo" block but not a "struct" parameter. Then produce above warning.

Issue reslove:
Greedy pop the "_ClassInfo" instance from the stack until "_ClassInfo" instance have open brace when ";" or ")" token is encountered.

### CODE REVIEW

**Comment by tkruse** [comment]
Thanks for reporting this. Could you add a unit test, too? If not, i can do that.  Also it might be nice to report it in the upstream repository.

**Comment by yanj403** [comment]
Appreciate if you can help on unit test, or help to send me any unit test guide.



---Original---
From: "Thibault ***@***.***&gt;
Date: Sat, Feb 12, 2022 11:13 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cpplint/cpplint] Fix issue when function arguments with mutiplyclass or struct keywords (PR #189)




 
Thanks for reporting this. Could you add a unit test, too? If not, i can do that.  Also it might be nice to report it in the upstream repository.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tkruse** [comment]
In https://github.com/cpplint/cpplint/blob/develop/cpplint_unittest.py#L3791, you can see a unit test for a simple empty struct. You can copy those lines and add your example there, and make sure no error is expected. something like:
```
 self.TestMultiLineLint(
        """
        struct D {
         struct demo_struct const *new_struct1,
          struct demo_struct const *new_struct2  
         };""",
        'Closing brace should be aligned with beginning of struct D'
        '')
```

**Comment by yanj403** [comment]
OK，I will add it.



---Original---
From: "Thibault ***@***.***&gt;
Date: Sat, Feb 12, 2022 12:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cpplint/cpplint] Fix issue when function arguments with mutiplyclass or struct keywords (PR #189)




 
In https://github.com/cpplint/cpplint/blob/develop/cpplint_unittest.py#L3791, you can see a unit test for a simple empty struct. You can copy those lines and add your example there, and make sure no error is expected. something like:
  self.TestMultiLineLint(         """         struct D {          struct demo_struct const *new_struct1,           struct demo_struct const *new_struct2            };""",         'Closing brace should be aligned with beginning of struct D'         '')  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yanj403** [comment]
The issue only happens on global functions, not typical cpp usage, so abandon this PR.
  
    struct demo_struct {
          int field;
      };
      
      void demo_issue(int num,
          struct demo_struct const *new_struct1,
          struct demo_struct const *new_struct2  
          )
      {
          return 0;
      }

**Pull request closed without merging**
