### PR TITLE
Add CI section / Mega-Linter

### PR DESCRIPTION
**Pull request by nvuillam**
If you have a header / logo, please notify me and i'll add it to your linter page :)

https://nvuillam.github.io/mega-linter/descriptors/c_cpplint/

https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/c_cpplint.md#readme

### CODE REVIEW

**Comment by nvuillam** [comment]
I have no idea why CI failed after just updates in README file :/  

image

**Comment by Migelo** [comment]
It failed because the python3.6 tests needs to be fixed. I just did that myself, see https://github.com/cpplint/cpplint/pull/164/commits/095d5979287a08bb8c778f152804d0127d67ae50.

**Comment by nvuillam** [comment]
@Migelo thanks for the tip, it's all good now :)

**Comment by tkruse** [comment]
HI, thanks for the MR. Mega-linter sure looks like a useful project, but it seems to me there may be quite many of such projects that include cpplint, so I am not sure why the README of cpplint should specifically mention mega-liner in the documentation. Though if the README had a section on similar and related projects, mega-linter would fit in.

**Comment by nvuillam** [comment]
@tkruse not "should" , but "could" :)

This is pretty common for linters to have a "Related projects" or "CI" section in their doc with such content :)

Examples: https://nvuillam.github.io/mega-linter/special-thanks/#sites-referring-to-mega-linter

But if you don't want to, no problem :)

**Comment by aaronliu0130** [comment]
Per tkruse. We're just a C++ linter 😅

**Pull request closed without merging**
