### PR TITLE
Better support for git submodule

### PR DESCRIPTION
**Pull request by cristiklein**
@tkruse 

With style fixed.

### CODE REVIEW

**Comment by cristiklein** [comment]
Hmm ... I got pylint failure for lines I did not touch. How come?

**Comment by tkruse** [comment]
OK, remaining travis problems are unrelated to this PR, fix already waiting in https://github.com/cpplint/cpplint/pull/55/commits/0071e61e (#55)

**Comment by cristiklein** [comment]
Shall I rebase?

**Comment by tkruse** [comment]
no, this is ok as is. I cannot currently merge, Matt said he'll find time again despite #49

**Comment by tkruse** [comment]
Hm, I think this should be looked again with #78. Not sure if they are duplicate or contradict each other.

**Comment by tkruse** [comment]
Also should modify the --root description to match behavior

**Comment by tkruse** [comment]
Related to  https://github.com/cpplint/cpplint/issues/37

**Pull request closed without merging**
