### PR TITLE
Add support for [[likely]] and misc brace bugfixes

### LINKED ISSUE #212: C++20 `[[likely]]` / `[[unlikely]]` attribute support
In [C++ attribute: `likely`, `unlikely` (since C++20)](https://en.cppreference.com/w/cpp/language/attributes/likely), we can add `[[likely]]` / `[[unlikely]]` on `if-else` clauses. But `cpplint` does not recognize the `[[likely]]` / `[[unlikely]]` attributes after `if` / `else` / `else if`:

Source file:

```cpp
// foo.cpp
// Copyright 2022 <test>

#include <iostream>

int fib1(int n) {
    if (n > 1) [[likely]] {
        int a;
        return fib1(n - 1) + fib1(n - 2);
    } else if (n == 2) [[unlikely]] {
        int b;
        return 1;
    } else [[unlikely]] {
        if (n == 1) [[likely]]
            return 1;
        else [[unlikely]]
            return 0;
    }
}

int fib2(int n) {
    switch (n) {
        [[unlikely]] case 0: return 0;
        case 1:
            [[fallthrough]];
        case 2:
            [[fallthrough]];
        [[unlikely]] case 3: {
            return 1;
        }
        [[likely]] default:
            return fib2(n - 1) + fib2(n - 2);
    }
}
```

Command-line:

```console
$ pip3 install -I git+https://github.com/cpplint/cpplint.git
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/cpplint/cpplint.git
  Cloning https://github.com/cpplint/cpplint.git to /tmp/pip-req-build-6nkph3fd
  Running command git clone --filter=blob:none --quiet https://github.com/cpplint/cpplint.git /tmp/pip-req-build-6nkph3fd
  Resolved https://github.com/cpplint/cpplint.git to commit fa12a0bbdafa15291276ddd2a2dcd2ac7a2ce4cb
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: cpplint
  Building wheel for cpplint (setup.py) ... done
  Created wheel for cpplint: filename=cpplint-1.6.1-py3-none-any.whl size=77266 sha256=3e95bbfd3de2b8d61d561339213e6a4ae741e8bb110b34c9b6f626c55cd325c9
  Stored in directory: /tmp/pip-ephem-wheel-cache-d42ge4uo/wheels/af/90/88/663d23197700a259f2a9199aef67ee9977e21f6d1980257857
Successfully built cpplint
Installing collected packages: cpplint
Successfully installed cpplint-1.6.1
```

```console
$ cpplint foo.cpp
foo.cpp:7:  If/else bodies with multiple statements require braces  [readability/braces] [4]
foo.cpp:10:  If/else bodies with multiple statements require braces  [readability/braces] [4]
foo.cpp:13:  Else clause should never be on same line as else (use 2 lines)  [whitespace/newline] [4]
foo.cpp:13:  If/else bodies with multiple statements require braces  [readability/braces] [4]
foo.cpp:16:  Else clause should never be on same line as else (use 2 lines)  [whitespace/newline] [4]
Done processing foo.cpp
Total errors found: 5
```

### PR DESCRIPTION
**Pull request by aaronliu0130**
This PR contains changes from #255 due to a mistake. That won't affect what'll be merged.

1. Fixes https://github.com/cpplint/cpplint/issues/212
2. else statements that have braces on both sides but have the second-to-last } on a separate line will no longer claim we need braces on both sides
3. Fix single-line if statements being yelled at to split their lines, something contradictory to the style guide
4. Fixes relevant tests, including adding the new "TestLintContains" and "TestLintNotContains" methods. (ik the latter may have a grammar error but who cares, this is consistent with the former's name)
5. Add a todo for "This exception does not apply to multi-keyword statements like if ... else or do ... while."

### CODE REVIEW

**Comment by aaronliu0130** [comment]
@jayvdb My implementation utilizes a feature from 3.8; 3.7 is EOL. Should we replace the 3.7 tests with 3.8 before releasing 1.7? Or should we do an implementation of the essential feature of handling [[(un)likely]] to put in 1.7, and release 1.7.1 with this? Or should we just release 1.7 as is and release 1.8 with this and maybe other stuff?

**Comment by aaronliu0130** [comment]
Hey @jayvdb, any thoughts? FYI The feature used is `:=` and I can probably port it to an implementation that doesn't use that without much issue, but the code will feel a lot more awkward.

**Comment by kpochwala** [comment]
Would love to see this merged, as currently it breaks pipeline with false positives.

**Comment by aaronliu0130** [comment]
It's not a false positive per se; it fails because it uses a language feature not present in 3.7, an EOL version. Anyways I'll merge this soon.

**Comment by aaronliu0130** [comment]
Closing to merge in #277

**Pull request closed without merging**
