### PR TITLE
Fix post increment/decrement operator causing a false positive.

### LINKED ISSUE #194: False positive when defining post-increment or post-decrement function in cpp file
The following causes a false positive `Using C-style cast.  Use static_cast<int>(...) instead  [readability/casting] [4]` error.

Test.hpp

```c++
struct Test
{
    Test operator++(int);
};
```

Test.cpp

```c++
#include "Test.hpp"

Test Test::operator++(int)
{
    return *this;
}
```

The issue is caused by the assumption that the `operator` keyword will always be prefixed with a space:

https://github.com/cpplint/cpplint/blob/35f28361aba21d3230b04241eeedc9ccff936632/cpplint.py#L5853

I propose that the condition is changed to the following:

```python
  if (context.endswith(' operator++') or context.endswith(' operator--') or
      context.endswith('::operator++') or context.endswith('::operator--')):
```

### PR DESCRIPTION
**Pull request by armandas**
Fixes #194

### CODE REVIEW

**Comment by tkruse** [comment]
Thanks for the report and the fix. It would be nice if you could also provide a unit test, else I will add one

**Comment by armandas** [comment]
@tkruse Thanks for the feedback. I added the tests. Could you check if it's OK?

**Comment by tkruse** [comment]
Code looks good, but github actions do not run tests... It seems the github action was not properly set up. Could you try rebasing (or merging master), so that this page shows the automatic checks?

**Comment by armandas** [comment]
Done.

**Comment by tkruse** [comment]
cool, looks good to me. Merged. Not sure when I will do next release... maybe after next open PR is merged

**Comment by armandas** [comment]
Thanks for your time, @tkruse!

**Pull request merged**
