### PR TITLE
Additional CLI syntax for file- and line-specific filters

### LINKED ISSUE #170: [feature] Provide line-specific NOLINT per command line
In addition to the `// NOLINT` in-line suppression, also allow to suppress specific lines via the command line interface.

Of course, in-line suppression is a neat thing but there are scenarios where one would not want to modify the source files but instead store all suppressions in a more global place.

### Comparison to Cppcheck

Cppcheck for example allows this like this (see https://linux.die.net/man/1/cppcheck):
> **--suppress=spec**
>
>    Suppress a specific warning. The format of <spec> is: [error id]:[filename]:[line]. The [filename] and [line] are optional. [error id] may be * to suppress all warnings (for a specified file or files). [filename] may contain the wildcard characters * or ?. 

Cppcheck examples:
- `--suppress=knownConditionTrueFalse:myFile.cpp:64`
- `--suppress=*:myOtherFile.cpp`

### In Cpplint
- Either extend the `--exclude` syntax or add a new `--suppress` parameter behaving like cppcheck.
- This would then also allow https://github.com/cpplint/cpplint/issues/137

Without knowing the inner workings of cpplint in detail, it seems like the CLI could add additional entries to `_error_suppressions` like it is done e.g. in `ParseNolintSuppressions()`

### PR DESCRIPTION
**Pull request by PhilLab**
Examples: 

    --filter=-whitespace:foo.h,+whitespace/braces:foo.h
    --filter=-whitespace,-runtime/printf:foo.h:14,+runtime/printf_format:foo.h
    --filter=-,+build/include_what_you_use:foo.h:321
    
Closes #170, #137

### CODE REVIEW

**Comment by PhilLab** [comment]
@tkruse I am unsure why two of the test runs failed

**Comment by tkruse** [comment]
Hello, thanks for creating the MR. The test failures seem unrelated to the changes, something I need to fix on the master branch.

I think the fix for the misleading documentation can be merged in any case.

For the new features, I am not so sure. Filtering error by line seems very awkward when source files change, all line numbers would have to be adapted, I have not seen other tools do this.

Having different filters per file also seems awkward, it seems to duplicate an approach where cpplint is invoked multiple times on different filesets. So I currently don't feel that positive about adding this as a new feature to support in the future, unless you can explain the benefit a bit more.

Also see the https://github.com/cpplint/cpplint/blob/develop/CONTRIBUTING.rst

**Comment by tkruse** [comment]
tests should be fixed after rebase. Also I see you have explained the comparison to cppcheck feature in #170, we should discuss there.

**Comment by jayvdb** [comment]
While I agree that filtering error by line does seem very awkward, I know of several use-cases for being able to have per file filters, and sometimes using inline cpplint comments is not permitted.  This is especially useful when one developer is trying to use cpplint to improve the code when other developers on the team are not yet ready.  Usually that process involves incrementally fixing the cpplint warnings until the list of inline exceptions needed is very small and very intentional.

**Comment by gkronin** [comment]
Could you, please, double-check the feature works when applied from under **CPPLINT.cfg** stored in the same folder as code.

**Pull request merged**
