### PR TITLE
Adds C++20 headers so they aren't flagged as c-style headers

### PR DESCRIPTION
**Pull request by miker2**

### CODE REVIEW

**Comment by miker2** [comment]
@tkruse @mattyclarkson Any hints on why CI seems to be failing? Seems to be due to a python dependency issue and unrelated to this change.

**Comment by tkruse** [comment]
HI @miker2 , thanks for the contribution. For the CI job, it seems tox 4.0 breaks the tox-pyenv plugin: https://github.com/tox-dev/tox-pyenv/issues/22. I changed to avoid tox 4.x until it gets fixed. If you rebase on master branch, it should be working.

**Comment by michael-projectx** [comment]
@tkruse Looks like after the rebase the PR is passing. Thanks for your help.

**Comment by tkruse** [comment]
cool, can you help me as a reviewer to check whether this list of headers is correct and complete? (E.g. do you have a reference list I could cross-check?)

**Comment by miker2** [comment]
Sure, I believe I pulled the headers from this list, by searching for "c++20": https://en.cppreference.com/w/cpp/header

**Comment by Bouncner** [comment]
Hi! Are there any plans to release a new tag? The last one is more than a year old and especially this PR here would be nice to be part of the lastest release.

**Pull request merged**
