### PR TITLE
Added 'size_t' to typecasts detected by CheckCStyleCast

### PR DESCRIPTION
**Pull request by Sidelobe**
Trivial PR .. but cpplint was not detecting `(size_t)` casts in my codebase

### CODE REVIEW

**Comment by tkruse** [comment]
thanks, the PR would be a little nicer with an added unit test for this case. Else I can add such a unit test myself.

**Comment by Sidelobe** [comment]
Absolutely— I’ll add a test to cover this new case :thumbs_up:

**Comment by Sidelobe** [comment]
@tkruse:  done - I've added a unit test. It's my first time contributing to this project, so please adjust or add additional tests if required.

**Comment by tkruse** [comment]
Thanks for adding the unit tests, looks good to me.

Currently some regression tests fail. That failure is because there are now additional warnings on those sample files taken from other existing projects: it seems there is one occurence of a size_t case in the sample files taken from the codelite project.

Stating the obvious for clarity: So if we merge this change, any project in the wild may start to see those additional warnings for locations using c-style casts involving size_t. It seems though this would be an improvement, so I am okay with the change.

The change required to make the tests pass is:
```
--- a/samples/codelite-sample/simple.def
+++ b/samples/codelite-sample/simple.def
@@ -3,7 +3,7 @@ src/*
 4
 Done processing src/pptable.cpp
 Done processing src/pptable.h
-Total errors found: 680
+Total errors found: 681
 
 src/pptable.cpp:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
 src/pptable.cpp:1:  Include the directory when naming .h files  [build/include_subdir] [4]
@@ -332,6 +332,7 @@ src/pptable.cpp:339:  Tab found; better to use spaces  [whitespace/tab] [1]
 src/pptable.cpp:341:  Tab found; better to use spaces  [whitespace/tab] [1]
 src/pptable.cpp:341:  Missing spaces around =  [whitespace/operators] [4]
 src/pptable.cpp:341:  Missing spaces around <  [whitespace/operators] [3]
+src/pptable.cpp:341:  Using C-style cast.  Use static_cast<size_t>(...) instead  [readability/casting] [4]
 src/pptable.cpp:342:  Tab found; better to use spaces  [whitespace/tab] [1]
 src/pptable.cpp:343:  Tab found; better to use spaces  [whitespace/tab] [1]
 src/pptable.cpp:345:  Tab found; better to use spaces  [whitespace/tab] [1]
```
@Sidelobe : Can you just confirm this change, that this would be a desirable message for the given line of code:
```
	int start = tmpString.Find(wxT("("));
	if(start == wxNOT_FOUND ) {
		return false;
	}
	tmpString = tmpString.Mid(start+1);

	for(size_t i=0; i<(size_t)start; i++) {
		initList << wxT(" ");
	}
```

**Comment by Sidelobe** [comment]
@tkruse: Thanks for updating the regression tests. Yes, that warning looks absolutely correct/expected to me. 👍

**Comment by tkruse** [comment]
no worries, I will add the test. It's manual.

**Comment by tkruse** [comment]
manually merged and released with 1.5.5

**Pull request closed without merging**
