### PR TITLE
Don't complain about `explicit` no-arg constructors.

### PR DESCRIPTION
**Pull request by markww**
Previously, cpplint has complained when a no-argument constructor is marked `explicit`. This is bad for two reasons:

1. As of C++11, converting constructors can be called with any number of arguments including 0. Therefore, this check is wrong. (see https://en.cppreference.com/w/cpp/language/converting_constructor )

2. Even in pre-C++-11 code, it is good defensive programming practice to mark all constructors `explicit`. Marking a constructor that cannot be a conversion `explicit` has no ill effect, but if someone alters it to be a possible implicit conversion, it defends you against them forgetting to add `explicit`.

### CODE REVIEW

**Comment by markww** [comment]
This failing check doesn't seem to be caused by my changes. Any guidance on how to get them to pass?

**Comment by aaronliu0130** [comment]
Note that the only change is c607830, I just merged to see if CI passes. I think that was a bad idea and I'll just run tox locally next time...

**Review by aaronliu0130 — APPROVED** [review]
Seems okay, but I'm not so experienced in that field. Is there any plausible reason you could think of for never marking zero-param constructors as explicit?

**Comment by geoffviola** [comment]
The Google style guide neither recommends nor forbids it.

https://google.github.io/styleguide/cppguide.html#Implicit_Conversions

Some C++ experts recommend it.

> Every other constructor (even the zero-argument constructor!) should be explicit or have a very well-understood domain-specific reason why not. Example: string(const char*).

https://quuxplusone.github.io/blog/2023/04/08/most-ctors-should-be-explicit/

> reverses the Cpp1 default, where constructors are not "explicit" by default, and you have to write "explicit" to make them explicit.

https://hsutter.github.io/cppfront/cpp2/types/#implicit-controlling-conversion-functions

There is probably room for a tool to warn against not having explicit for non-move/copy/initializer list constructors. But the need seems small.

**Pull request merged**
