### PR TITLE
Reduce diff between fork and upstream by using xrange again

### PR DESCRIPTION
**Pull request by tkruse**

### CODE REVIEW

**Comment by cclauss** [comment]
__xrange()__ was removed in Python 3. 
* https://docs.python.org/3/whatsnew/3.0.html#views-and-iterators-instead-of-lists
* https://portingguide.readthedocs.io/en/latest/iterators.html#new-behavior-of-range

**Comment by tkruse** [comment]
Fair enough. Though it's google:gh-pages that counts, this repo is not diverged much.

**Comment by tkruse** [comment]
To be more precise, with the 1.4.x branch cpplint/cpplint should be up-to-date again with all merged changes in upstream up to 2019.

AFAIK, Google maintains the actual files in some in-house wiki, they have a tool called Copybara which updates their github styleguide repo and **gh-pages branch** by extracting from that wiki. Which I guess explains also why several styleguides are checked in as HTML.

The master branch of the upstream repo (https://github.com/google/styleguide/tree/master) only has one commit, it is dead and looks like somebody made a mistake setting up their syncing tool.

**Comment by tkruse** [comment]
Hm, so back to the topic:

* We can either try to reduce the diff to google, to make including upstream patches easier. That would mean do whatever google does.
* Or we can try to be more Python3 compliant by using range everywhere. But with python2, this might not have optimal performance.

The current state of using both range and xrange, but in some places different from upstream, seems achieving neither purpose. What do you think @cclauss ?

**Comment by cclauss** [comment]
> with python2, this might not have optimal performance.

That sub-optimal performance is negligible unless the range is massive and with 317 days until Python 2 end of life, most folks are erring on the side of simple compatibility.

The alternative is to use the __try / except NameError:__ approach that was used in google/styleguide#332 or use [__six__](https://six.readthedocs.io/) or [__future__](https://python-future.org/)

**Comment by tkruse** [comment]
So you would prefer to use `range` everywhere, for syntactic python3 compliance?
In general I think this would be the better code, but the goal of this fork is to stay close to upstream, and make changes only when they make upstream cpplint usable in more contexts. Being Python3-compatible was a reason to redefine xrange, but being Python3 syntax compliant is not strictly justified by the forks mission. So I am dispassionate, need more time to think maybe.

**Comment by cclauss** [comment]
What is the "html source" that Copybara uses for upstream because I still can not figure out why google#332 did not fix the problem?

**Comment by tkruse** [comment]
The 'html' source has nothing to do with cpplint, it's other textual styleguide in the upstream repo, such as https://github.com/google/styleguide/blob/gh-pages/javaguide.html.

https://github.com/google/styleguide/pull/332 added `xrange = range` for python3 compatibility, but now you seem to be saying we should be using `range` instead of "`range`, saying "We want to remain compatible with modern Python. **xrange()** was removed in Python 3." in your response above.

Since https://github.com/google/styleguide/pull/332 did not replace `xrange` with `range` everywhere in the code, I am not sure what the general philosophy is. Should the cpplint fork move ahead with using range everywhere, or use the same function as upstream, or use xrange everywhere?

https://github.com/google/styleguide/pull/332 does not help in making that decision.

**Comment by cclauss** [comment]
Oh...  Now I see.  My mistake.  You can reopen this PR and I will support it.  I failed to notice [these lines](https://github.com/cpplint/cpplint/blob/master/cpplint.py#L62-L66) which allow for the use of __xrange()__ in Python 3.

**Pull request merged**
