### PR TITLE
Search all headers extensions for first include

### LINKED ISSUE #102: CheckHeaderFileIncluded() too restrictive
The current implementation of CheckHeaderFileIncluded() fails the following case (randomly):

```
  a.c   -> includes a.h
  a.h
  a.cpp -> includes a.hpp
  a.hpp
```

I think that this case (multiple basenames with different extensions) should be allowed.

### PR DESCRIPTION
**Pull request by crogre**
When checking that the first include file is the associated header file
in [build/include], all allowed headers should be searched before
failing test.

Example that this patch will pass that fails (randomly) otherwise:

  a.c   -> includes a.h
  a.h
  a.cpp -> includes a.hpp
  a.hpp

### CODE REVIEW

**Comment by crogre** [comment]
Closes #102

**Comment by tkruse** [comment]
The unit tests don't pass. Also it would be nice if there was a new test for the changed code.

**Comment by jayvdb** [comment]
Please start a new PR with the desired changes.

**Comment by aaronliu0130** [comment]
Why? The merge conflict can be resolved. It’s just one unindenting, though we’d probably have to write tests for it

**Comment by jayvdb** [comment]
The merge conflict has not been resolved, and the tests do not pass.

**Comment by aaronliu0130** [comment]
I'll resolve them then. (It's just removing one layer of indentation, it's easy to resolve. Many of the other PRs merged had their conflicts resolved by me.) I'll also look at if the problem exists myself.

**Review by jayvdb — APPROVED** [review]
As this is hard to reproduce, it would be very helpful to have a unit-test for this.  Anyway, approved.

**Pull request merged**
