### PR TITLE
Fix #135: allow 'if constexpr' in readability/braces.

### LINKED ISSUE #135: 'else if constexpr' fails with readability/braces
"If/else bodies with multiple statements require braces  [readability/braces] " error is given for code like

```cpp
if constexpr (foo) {
...
} else if constexpr (bar) {
...
} else {
...
}
```

while 

```cpp
if (foo) {
...
} else if (bar) {
...
} else {
...
}
```

is fine.

### PR DESCRIPTION
**Pull request by Shachlan**

### CODE REVIEW

**Comment by Shachlan** [comment]
@tkruse, can you please help me with this? I don't understand how to run the python scripts locally and find out the issue with the CI, and the error message that is printed in the CI isn't very informative.

**Comment by tkruse** [comment]
CI should be fixed on master, now. I also could not reproduce locally, not sure why certain library versions that do not work with python 2.7 are being pulled on travis.

**Comment by Shachlan** [comment]
@tkruse, thanks. rebased.

**Comment by tkruse** [comment]
The git history looks weird: https://github.com/Shachlan/cpplint/commits/if-constexpr. Latest commit on master should be 2af9d96e77a88 "freeze versions for python 2.7, fix setup.py for comments breaking pip". Not even sure why travis now passed. But I think the code can be merged anyway for next release.

**Comment by Shachlan** [comment]
Fixed the history - it was because I was rebased over my own fork.

**Pull request merged**
