### PR TITLE
Add a pyproject.toml file

### PR DESCRIPTION
**Pull request by vyasr**
By explicitly specifying the legacy setuptools build backend via pyproject.toml, we ensure that the current directory is visible to the setup.py invocation. Without this, in some environments I observe that pip installing the sdist or a clone of the repo fails because the current directory is not on the PYTHONPATH (for instance, using cpplint as a pre-commit hook fails for me on some Python/pip versions). Note that this is because the setup.py in this repo imports the cpplint module from the current directory, and for this reason it is necessary to specify that the build backend is `setuptools.build_meta:__legacy__`, not just `setuptools.build_meta`.

### CODE REVIEW

**Comment by vyasr** [comment]
I don't fully know how to read the output, but it looks like the failing test is because the index of something in a list of errors has changed from 5 to 4:
```
  E       -'src/descriptor_unittest.cc:5929:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]\n'
  E       -'src/descriptor_unittest.cc:5968:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [5]\n'
  E       +'src/descriptor_unittest.cc:5929:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [4]\n'
  E       +'src/descriptor_unittest.cc:5968:  Single-parameter constructors should be marked explicit.  [runtime/explicit] [4]\n'
```
It may be related to this changeset insofar as the output of some build step could like quite different now because pip outputs different lines (and runs some different setup) solely on the basis of pyproject.toml existing. That's just a guess, though; I'm afraid I don't really know what this test is intended for.

**Comment by aaronliu0130** [comment]
Yes, it's unrelated. See #268. Unfortunately, our other maintainer @jayvdb is not active, and we cannot merge our own PRs.

I'll use a sockpuppet to just get that fix in.

**Comment by aaronliu0130** [comment]
Merged. @vyasr Could you sync with our latest commit?

**Comment by vyasr** [comment]
Merged the latest develop, thanks!

**Review by aaronliu0130 — APPROVED** [review]
lgtm, hopefully we can get the entire setup.py converted to toml someday!

**Pull request merged**
