### PR TITLE
Remove Class And Namespace Complete Checks

### PR DESCRIPTION
**Pull request by geoffviola**
This PR renames one of the `build/namespaces` checks from `build/namespaces` to `build/namespaces_complete`. The check warns against non closed namespaces. This change should enable using `build/namespaces` in a more fine-grained manner.

### CODE REVIEW

**Comment by geoffviola** [comment]
I'm not sure if the checks in `CheckCompletedBlocks` provide much value. It seems like the compiler should check these.

**Review by aaronliu0130 — CHANGES_REQUESTED** [review]
I agree that we probably shouldn't check this unless it would otherwise result in false positives (due to NestingState, I don't think that'll happen.). However, if we're renaming this, wouldn't build/namespaces/complete or even build/complete/namespaces be a better name? Personally I'd prefer removing the checks unless you have any objections.

**Comment by geoffviola** [comment]
I made the change more aggressive. It eliminates both the completed class and namespace checks. That should be less to maintain.

**Review by aaronliu0130 — APPROVED** [review]
Looks okay, though I may or may not want an additional opinion from @jayvdb, and you should add this part to the changelog.

**Pull request merged**
