### PR TITLE
Rename changelog.rst to CHANGELOG.rst

### PR DESCRIPTION
**Pull request by ember91**
Apparently it was renamed, breaking some documentation in the process.

### CODE REVIEW

**Review by aaronliu0130 — CHANGES_REQUESTED** [review]
I was thinking about this a while ago and would actually prefer the opposite: renaming changelog.rst to CHANGELOG.rst so it's consistent with other documentation.

**Comment by ember91** [comment]
Yes. Do want you want here. To me it does not matter.

**Comment by aaronliu0130** [comment]
Thanks, but it'd be easier for all of us here if you committed the changes to your own branch, since we have mandatory review here yet all the other maintainers are inactive while I do not have the power to add other maintainers.

**Comment by ember91** [comment]
> Thanks, but it'd be easier for all of us here if you committed the changes to your own branch, since we have mandatory review here yet all the other maintainers are inactive while I do not have the power to add other maintainers.

Can you have a look now?

**Review by aaronliu0130 — APPROVED** [review]
Sorry for the long delay, I had some academci commitments. LGTM!

**Pull request merged**
