### PR TITLE
Err on functions indented inside namespaces

### LINKED ISSUE #234: Lint is not working for catching Namespace Indentation error
Hello, i found some error related to indentation and it seems worth it to solve.

In google style guide, there is the contents for namespace indentation
https://google.github.io/styleguide/cppguide.html#Namespace_Formatting
Specifying 'the contents of namespace are not indented'.

For example,
image
You can see there is indent inside in namespace scope.
This is not fit to google style guide.

image
This is the example of correct style refer to google style guide.

And as you can see, 
image
lint is not catching!

I think it would be great that if this problem solved.
Can anyone give comments or feedback for this issue?

Thankyou!

### PR DESCRIPTION
**Pull request by Yujinmon**
Hello, 
As i mentioned in issue #234 , i noticed there is error in namespace indentation.
Refer to google style guide, there have to be no function indentation inside of namespace scope.
But lint couldn't catch it.

So i changed 
image

like this, and checked it works well.
image

Honestly I could prove excatly why, But It would be appreciated if you could check.

Thank you

### CODE REVIEW

**Comment by aaronliu0130** [comment]
The PR currently fails on the following testcase:
```cpp
	namespace Test{
	void foo() { }
	}  // namespace Test
```
Note the leading whitespace.

**Review by aaronliu0130 — APPROVED** [review]

**Comment by cvvergara** [comment]
Hi all
I normally use `develop` branch on pgRouting's CI

I can see you are aware of the problem on develop with this PR.

https://github.com/cvvergara/pgrouting/actions/runs/8868982380/job/24349155971#step:4:77
https://github.com/pgrouting/pgrouting/blob/develop/src/alpha_shape/pgr_alphaShape.cpp#L321-L324

The common place I see this happen is when the parameters of a function within a namespace are indented


Note that if the code is wrapped with `#if 0` `#endif` it also generates the error

https://github.com/cvvergara/pgrouting/actions/runs/8868982380/job/24349155971#step:4:84
https://github.com/cvvergara/pgrouting/blob/develop/src/bellman_ford/bellman_ford_driver.cpp#L55

The filter `--filter=-whitespace/indent_namespace` works ok

**Comment by aaronliu0130** [comment]
I will check this out. Note that our other maintainer has been inactive, so merging the eventual fix may take some time due to the review requirement.

**Comment by aaronliu0130** [comment]
This would involve refactoring state to also keep track of function parameter nesting (and ideally template argument nesting too).

**Pull request merged**
