### PR TITLE
add elif as an exception for CheckSpacingForFunctionCall()

### PR DESCRIPTION
**Pull request by Migelo**
The current version of the code allows for white spaces after preprocessor directive `#if (FOO == 1)` but not after `#elif (FOO == 1)`.

The code below will throw this error: test.cpp:4:  Extra space before ( in function call  [whitespace/parens] [4]

```
int main() {
#if (A == 0)
    foo();
#elif (A == 1)
    bar();
#endif
return 0;
}
```
This pull request fixes that.

### CODE REVIEW

**Comment by tkruse** [comment]
Thanks for the PR. It would be even nicer if there was a change to a unit test for #elif. But I can add that myself, too.

**Comment by Migelo** [comment]
I'll add the test.

**Comment by Migelo** [comment]
Could we drop python3.5? Is is not being supported.
https://en.wikipedia.org/wiki/History_of_Python

I will try to fix the failing 2.7 build.

**Comment by tkruse** [comment]
ok to drop 3.5

**Comment by tkruse** [comment]
thanks for all the fixes, I hope the develop branch should build again: https://travis-ci.org/github/cpplint/cpplint/builds/754275763, then we could rebase and merge

**Comment by tkruse** [comment]
manually merged

**Comment by tkruse** [comment]
released today with 1.5.5. Sorry for the delay.

**Pull request closed without merging**
